# Generated by Django 2.2.5 on 2019-12-04 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20191204_1511'),
    ]

    operations = [
        migrations.DeleteModel(
            name='New_camera_type_db',
        ),
        migrations.DeleteModel(
            name='New_location_db',
        ),
    ]
