# Generated by Django 2.2.5 on 2019-12-04 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_auto_20191204_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser_db',
            fields=[
                ('u_name', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('p_word', models.CharField(max_length=70)),
                ('u_role', models.CharField(max_length=70)),
            ],
        ),
    ]
